<a href="https://colab.research.google.com/github/Emirat17/Bayesian/blob/main/Covid_Gap_Montecarlo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files

from google.colab import files
uploaded = files.upload()

Saving data_covid.xlsx to data_covid.xlsx


In [6]:
import io
data = pd.read_excel(io.BytesIO(uploaded['data_covid.xlsx']))
data_covid = data

In [3]:
data.head()

Tanggal  PROBABLE  SUSPEK  POSITIF  SEMBUH  MENINGGAL
0  2020-09-02 00:00:00        42     243      518    4967        630
1  2020-09-03 00:00:00        39     404      519    5077        636
2  2020-09-04 00:00:00        46     441      482    5198        640
3  2020-09-05 00:00:00        51     486      460    5325        644
4  2020-09-06 00:00:00        58     465      483    5402        648

In [4]:
data.tail()

Tanggal  PROBABLE  SUSPEK  POSITIF  SEMBUH  MENINGGAL
262  2021-05-22 00:00:00        20      59      398   34328       2881
263  2021-05-23 00:00:00        24      56      385   34433       2886
264  2021-05-24 00:00:00        31      70      358   34480       2894
265  2021-05-25 00:00:00        23      95      392   34594       2900
266  2021-05-26 00:00:00        22      83      401   34692       2906

In [7]:
data = data.loc[0:246,]

In [8]:
data.tail()

Tanggal  PROBABLE  SUSPEK  POSITIF  SEMBUH  MENINGGAL
242  2021-05-02 00:00:00        12      62      313   32829       2773
243  2021-05-03 00:00:00        15      67      286   32891       2776
244  2021-05-04 00:00:00         9      62      292   32969       2783
245  2021-05-05 00:00:00         9      65      313   33085       2792
246  2021-05-06 00:00:00        12      69      309   33159       2799

Let's first use monte carlo simulation for forecasting 

1. Prediksi Jumlah Kasus "POSITIF"

In [9]:
from scipy.stats import norm
log_returns = np.log(1 + data.POSITIF.pct_change())
u = log_returns.mean() #Mean of the logarithmich return
var = log_returns.var() #Variance of the logarithic return
drift = u - (0.5 * var) #drift / trend of the logarithmic return
stdev = log_returns.std() #Standard deviation of the log return


t_intervals = 20 #I just wanted to forecast 250 time points
iterations = 10000 #I wanted to have 10 different forecast

import random
np.random.seed(10)
daily_returns = np.exp(drift + stdev * norm.ppf(np.random.rand(t_intervals, iterations)))
#daily_returns actually is some kind of a noise. When we multiply this with the t time price, we can obtain t+1 time price

Let's create a variable S0 (inital stock price) equals to the last  closing price .

In [10]:
S0 = data.POSITIF.iloc[-1]
S0

309

In [11]:
#Let us first create en empty matrix such as daily returns
pos_list = np.zeros_like(daily_returns)
pos_list[0] = S0
pos_list

array([[309., 309., 309., ..., 309., 309., 309.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [12]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    pos_list[t] = pos_list[t - 1] * daily_returns[t]
pos_list = pd.DataFrame(pos_list)
pos_list.head()

0           1           2     ...        9997        9998        9999
0  309.000000  309.000000  309.000000  ...  309.000000  309.000000  309.000000
1  304.749497  339.169314  307.045854  ...  335.880068  351.603715  332.272837
2  316.121760  363.493757  332.088938  ...  345.891683  349.130189  325.668633
3  308.739430  348.492279  327.393250  ...  319.484401  348.119327  335.201051
4  317.071864  365.092920  347.926402  ...  314.682108  356.045371  323.247513

[5 rows x 10000 columns]

In [13]:
positif = data.POSITIF
positif = pd.DataFrame(positif)
frames = [positif, pos_list]
monte_carlo_forecast = pd.concat(frames)

In [14]:
#Let us first create en empty matrix such as daily returns
pos_list = np.zeros_like(daily_returns)
pos_list[0] = S0
pos_list

array([[309., 309., 309., ..., 309., 309., 309.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [15]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    pos_list[t] = pos_list[t - 1] * daily_returns[t]

In [16]:
positif_new = np.zeros([t_intervals,1])
positif_new

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [17]:
for t in range(0, t_intervals):
  positif_new[t] = sum(pos_list[t,:])/iterations
positif_new
#positif_new = pd.DataFrame(positif_new)
#positif_new.head()

array([[309.        ],
       [308.31467186],
       [307.68474294],
       [307.27651943],
       [306.5221135 ],
       [305.54511286],
       [304.90510658],
       [304.21776047],
       [303.56780554],
       [302.90258975],
       [302.11379624],
       [301.60700781],
       [300.85534115],
       [300.23747338],
       [299.74695113],
       [299.04199469],
       [298.41801017],
       [298.0088158 ],
       [297.45521577],
       [296.8828666 ]])

In [26]:
real = np.array(data_covid.loc[247:,'POSITIF'])

In [27]:
gap = np.zeros([20,1])
for t in range(0, t_intervals):
  gap[t] = abs(real[t]-positif_new[t])/real[t]*100

In [28]:
real = real.reshape((20,1))
real.shape
real

array([[328],
       [334],
       [364],
       [347],
       [413],
       [395],
       [377],
       [355],
       [349],
       [340],
       [339],
       [374],
       [392],
       [409],
       [395],
       [398],
       [385],
       [358],
       [392],
       [401]])

In [29]:
positif_new = pd.DataFrame(positif_new)
real = pd.DataFrame(real)
gap = pd.DataFrame(gap)

In [30]:
tabel = pd.DataFrame(real)

In [31]:
tabel['prediksi'] = positif_new
tabel['gap'] = gap

In [32]:
tabel

0    prediksi        gap
0   328  309.000000   5.792683
1   334  308.314672   7.690218
2   364  307.684743  15.471224
3   347  307.276519  11.447689
4   413  306.522114  25.781571
5   395  305.545113  22.646807
6   377  304.905107  19.123314
7   355  304.217760  14.304856
8   349  303.567806  13.017821
9   340  302.902590  10.911003
10  339  302.113796  10.880886
11  374  301.607008  19.356415
12  392  300.855341  23.251188
13  409  300.237473  26.592305
14  395  299.746951  24.114696
15  398  299.041995  24.863820
16  385  298.418010  22.488829
17  358  298.008816  16.757314
18  392  297.455216  24.118567
19  401  296.882867  25.964372

2. Prediksi Jumlah Kasus "SUSPEK"

In [33]:
from scipy.stats import norm
log_returns = np.log(1 + data.SUSPEK.pct_change())
u = log_returns.mean() #Mean of the logarithmich return
var = log_returns.var() #Variance of the logarithic return
drift = u - (0.5 * var) #drift / trend of the logarithmic return
stdev = log_returns.std() #Standard deviation of the log return


t_intervals = 20 #I just wanted to forecast 250 time points
iterations = 10000 #I wanted to have 50 different forecast

import random
np.random.seed(10)
daily_returns = np.exp(drift + stdev * norm.ppf(np.random.rand(t_intervals, iterations)))
#daily_returns actually is some kind of a noise. When we multiply this with the t time price, we can obtain t+1 time price

Let's create a variable S0 (inital).

In [34]:
S0 = data.SUSPEK.iloc[-1]
S0

69

In [42]:
#Let us first create en empty matrix such as daily returns
sus_list = np.zeros_like(daily_returns)
sus_list[0] = S0
sus_list

array([[69., 69., 69., ..., 69., 69., 69.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [43]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    sus_list[t] = sus_list[t - 1] * daily_returns[t]
sus_list = pd.DataFrame(sus_list)
sus_list.head()

0          1          2     ...       9997       9998       9999
0  69.000000  69.000000  69.000000  ...  69.000000  69.000000  69.000000
1  66.502023  84.917815  67.652295  ...  83.048256  92.197611  81.024823
2  71.930034  98.955931  80.500088  ...  88.348159  90.249146  76.988909
3  67.794528  89.403853  77.516757  ...  73.305266  89.185435  81.804625
4  71.670850  98.912671  88.607702  ...  70.442835  93.402057  74.899694

[5 rows x 10000 columns]

In [44]:
suspek = data.SUSPEK
suspek = pd.DataFrame(suspek)
frames = [suspek, sus_list]
monte_carlo_forecast = pd.concat(frames)

In [45]:
#Let us first create en empty matrix such as daily returns
sus_list = np.zeros_like(daily_returns)
sus_list[0] = S0
sus_list

array([[69., 69., 69., ..., 69., 69., 69.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [46]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    sus_list[t] = sus_list[t - 1] * daily_returns[t]

In [47]:
suspek_new = np.zeros([t_intervals,1])
suspek_new

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [48]:
for t in range(0, t_intervals):
  suspek_new[t] = sum(sus_list[t,:])/iterations
#suspek_new = pd.DataFrame(suspek_new)
#suspek_new.head()

Perbandingan Gap antara hasil prediksi dengan data real.

In [51]:
real = np.array(data_covid.loc[247:,'SUSPEK'])
real

array([72, 70, 71, 82, 77, 62, 70, 68, 76, 85, 85, 88, 86, 60, 57, 59, 56,
       70, 95, 83])

In [52]:
gap = np.zeros([20,1])
for t in range(0, t_intervals):
  gap[t] = abs(real[t]-suspek_new[t])/real[t]*100

In [53]:
real = real.reshape((20,1))
real.shape
real

array([[72],
       [70],
       [71],
       [82],
       [77],
       [62],
       [70],
       [68],
       [76],
       [85],
       [85],
       [88],
       [86],
       [60],
       [57],
       [59],
       [56],
       [70],
       [95],
       [83]])

In [54]:
suspek_new = pd.DataFrame(suspek_new)
real = pd.DataFrame(real)
gap = pd.DataFrame(gap)

In [55]:
tabel = pd.DataFrame(real)

In [56]:
tabel['prediksi'] = suspek_new
tabel['gap'] = gap

In [57]:
tabel

0   prediksi        gap
0   72  69.000000   4.166667
1   70  68.636490   1.947872
2   71  68.278424   3.833206
3   82  68.053630  17.007768
4   77  67.656207  12.134797
5   62  67.136380   8.284484
6   70  66.798353   4.573781
7   68  66.437614   2.297626
8   76  66.092579  13.036080
9   85  65.750694  22.646242
10  85  65.322073  23.150502
11  88  65.037530  26.093716
12  86  64.638837  24.838561
13  60  64.327194   7.211990
14  57  64.047504  12.364043
15  59  63.703319   7.971727
16  56  63.372031  13.164341
17  70  63.144466   9.793620
18  95  62.888311  33.801778
19  83  62.618370  24.556181

3. Prediksi Jumlah Kasus "PROBABLE"

In [131]:
from scipy.stats import norm
log_returns = np.log(1 + data.PROBABLE.pct_change())
u = log_returns.mean() #Mean of the logarithmich return
var = log_returns.var() #Variance of the logarithic return
drift = u - (0.5 * var) #drift / trend of the logarithmic return
stdev = log_returns.std() #Standard deviation of the log return

t_intervals = 20 #I just wanted to forecast 250 time points
iterations = 10000 #I wanted to have 50 different forecast

import random
np.random.seed(10)
daily_returns = np.exp(drift + stdev * norm.ppf(np.random.rand(t_intervals, iterations)))
#daily_returns actually is some kind of a noise. When we multiply this with the t time price, we can obtain t+1 time price

Let's create a variable S0 (inital).

In [132]:
S0 = data.PROBABLE.iloc[-1]
S0

12

In [133]:
#Let us first create en empty matrix such as daily returns
prob_list = np.zeros_like(daily_returns)
prob_list[0] = S0
prob_list

array([[12., 12., 12., ..., 12., 12., 12.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [134]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    prob_list[t] = prob_list[t - 1] * daily_returns[t]
prob_list = pd.DataFrame(prob_list)
prob_list.head()

0          1          2     ...       9997       9998       9999
0  12.000000  12.000000  12.000000  ...  12.000000  12.000000  12.000000
1  11.434693  15.583539  11.685733  ...  15.150347  17.294241  14.684421
2  12.609539  18.885557  14.541410  ...  16.359455  16.806492  13.742934
3  11.680382  16.581533  13.840772  ...  12.895492  16.530250  14.817353
4  12.512958  18.816349  16.369228  ...  12.242075  17.498820  13.231068

[5 rows x 10000 columns]

In [135]:
probable = data.PROBABLE
probable = pd.DataFrame(probable)
frames = [probable, prob_list]
monte_carlo_forecast = pd.concat(frames)

In [136]:
#Let us first create en empty matrix such as daily returns
prob_list = np.zeros_like(daily_returns)
prob_list[0] = S0
prob_list

array([[12., 12., 12., ..., 12., 12., 12.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [137]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    prob_list[t] = prob_list[t - 1] * daily_returns[t]

In [138]:
probable_new = np.zeros([t_intervals,1])
probable_new

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [139]:
for t in range(0, t_intervals):
  probable_new[t] = sum(prob_list[t,:])/iterations
#probable_new = pd.DataFrame(probable_new)
#probable_new.head()

Perbandingan Gap antara hasil prediksi dengan data real.

In [140]:
real = np.array(data_covid.loc[247:,'PROBABLE'])
real

array([12, 18, 26, 27, 20, 20, 19, 20, 19, 17, 17, 16, 17, 22, 22, 20, 24,
       31, 23, 22])

In [141]:
gap = np.zeros([20,1])
for t in range(0, t_intervals):
  gap[t] = abs(real[t]-probable_new[t])/real[t]*100

In [142]:
real = real.reshape((20,1))
real.shape
real

array([[12],
       [18],
       [26],
       [27],
       [20],
       [20],
       [19],
       [20],
       [19],
       [17],
       [17],
       [16],
       [17],
       [22],
       [22],
       [20],
       [24],
       [31],
       [23],
       [22]])

In [143]:
probable_new = pd.DataFrame(probable_new)
real = pd.DataFrame(real)
gap = pd.DataFrame(gap)

In [144]:
tabel = pd.DataFrame(real)

In [145]:
tabel['prediksi'] = probable_new
tabel['gap'] = gap

In [146]:
tabel

0   prediksi        gap
0   12  12.000000   0.000000
1   18  11.937274  33.681810
2   26  11.873179  54.333925
3   27  11.840649  56.145745
4   20  11.769978  41.150111
5   20  11.671419  41.642903
6   19  11.613665  38.875446
7   20  11.550180  42.249101
8   19  11.489802  39.527359
9   17  11.431772  32.754283
10  17  11.351442  33.226813
11  16  11.302460  29.359624
12  17  11.229379  33.944831
13  22  11.178059  49.190641
14  22  11.129627  49.410787
15  20  11.071633  44.641837
16  24  11.012144  54.116066
17  31  10.974927  64.597009
18  23  10.937511  52.445603
19  22  10.894966  50.477429

3. Prediksi Jumlah Kasus "MENINGGAL"

In [95]:
from scipy.stats import norm
log_returns = np.log(1 + data.MENINGGAL.pct_change())
u = log_returns.mean() #Mean of the logarithmich return
var = log_returns.var() #Variance of the logarithic return
drift = u - (0.5 * var) #drift / trend of the logarithmic return
stdev = log_returns.std() #Standard deviation of the log return

t_intervals = 20 #I just wanted to forecast 250 time points
iterations = 10000 #I wanted to have 10 different forecast

import random
np.random.seed(10)
daily_returns = np.exp(drift + stdev * norm.ppf(np.random.rand(t_intervals, iterations)))
#daily_returns actually is some kind of a noise. When we multiply this with the t time price, we can obtain t+1 time price

Let's create a variable S0 (inital).

In [96]:
S0 = data.MENINGGAL.iloc[-1]
S0

2799

In [97]:
#Let us first create en empty matrix such as daily returns
dead_list = np.zeros_like(daily_returns)
dead_list[0] = S0
dead_list

array([[2799., 2799., 2799., ..., 2799., 2799., 2799.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       ...,
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [98]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    dead_list[t] = dead_list[t - 1] * daily_returns[t]
dead_list = pd.DataFrame(dead_list)
dead_list['meninggal'] = dead_list[0]
dead_list.head()

0            1            2  ...         9998         9999    meninggal
0  2799.000000  2799.000000  2799.000000  ...  2799.000000  2799.000000  2799.000000
1  2813.832080  2836.856757  2815.441208  ...  2844.646127  2832.422053  2813.832080
2  2839.640186  2869.998015  2850.316251  ...  2861.199513  2846.081706  2839.640186
3  2852.562525  2878.995912  2865.335241  ...  2878.761156  2870.482776  2852.562525
4  2876.532946  2907.592688  2896.947945  ...  2902.041489  2880.761782  2876.532946

[5 rows x 10001 columns]

In [99]:
meninggal = data.MENINGGAL
meninggal = pd.DataFrame(meninggal)
frames = [meninggal, dead_list]
monte_carlo_forecast = pd.concat(frames)

In [100]:
#Let us first create en empty matrix such as daily returns
dead_list = np.zeros_like(daily_returns)
dead_list[0] = S0
dead_list

array([[2799., 2799., 2799., ..., 2799., 2799., 2799.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       ...,
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [101]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    dead_list[t] = dead_list[t - 1] * daily_returns[t]

In [102]:
meninggal_new = np.zeros([t_intervals,1])
meninggal_new

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [103]:
for t in range(0, t_intervals):
  meninggal_new[t] = sum(dead_list[t,:])/iterations
#meninggal_new = pd.DataFrame(meninggal_new)
#meninggal_new.head()

Perbandingan Gap antara hasil prediksi dengan data real.

In [106]:
real = np.array(data_covid.loc[247:,'MENINGGAL'])
real

array([2799, 2808, 2815, 2818, 2819, 2822, 2830, 2832, 2840, 2845, 2847,
       2862, 2870, 2875, 2878, 2881, 2886, 2894, 2900, 2906])

In [107]:
gap = np.zeros([20,1])
for t in range(0, t_intervals):
  gap[t] = abs(real[t]-meninggal_new[t])/real[t]*100

In [108]:
real = real.reshape((20,1))
real.shape
real

array([[2799],
       [2808],
       [2815],
       [2818],
       [2819],
       [2822],
       [2830],
       [2832],
       [2840],
       [2845],
       [2847],
       [2862],
       [2870],
       [2875],
       [2878],
       [2881],
       [2886],
       [2894],
       [2900],
       [2906]])

In [109]:
meninggal_new = pd.DataFrame(meninggal_new)
real = pd.DataFrame(real)
gap = pd.DataFrame(gap)

In [110]:
tabel = pd.DataFrame(real)

In [111]:
tabel['prediksi'] = meninggal_new
tabel['gap'] = gap

In [112]:
tabel

0     prediksi       gap
0   2799  2799.000000  0.000000
1   2808  2815.985610  0.284388
2   2815  2833.135794  0.644256
3   2818  2850.528454  1.154310
4   2819  2867.777862  1.730325
5   2822  2884.986086  2.231966
6   2830  2902.525553  2.562740
7   2832  2920.130324  3.111946
8   2840  2937.873675  3.446256
9   2845  2955.709536  3.891372
10  2847  2973.585294  4.446270
11  2862  2991.772684  4.534336
12  2870  3009.882277  4.873947
13  2875  3028.184350  5.328151
14  2878  3046.723213  5.862516
15  2881  3065.172742  6.392667
16  2886  3083.811756  6.854184
17  2894  3102.728173  7.212446
18  2900  3121.627276  7.642320
19  2906  3140.612552  8.073384

4. Prediksi Jumlah Kasus "SEMBUH"

In [113]:
from scipy.stats import norm
log_returns = np.log(1 + data.SEMBUH.pct_change())
u = log_returns.mean() #Mean of the logarithmich return
var = log_returns.var() #Variance of the logarithic return
drift = u - (0.5 * var) #drift / trend of the logarithmic return
stdev = log_returns.std() #Standard deviation of the log return

t_intervals = 20 #I just wanted to forecast 250 time points
iterations = 10000 #I wanted to have 10 different forecast

import random
np.random.seed(10)
daily_returns = np.exp(drift + stdev * norm.ppf(np.random.rand(t_intervals, iterations)))
#daily_returns actually is some kind of a noise. When we multiply this with the t time price, we can obtain t+1 time price

Let's create a variable S0 (inital).

In [114]:
S0 = data.SEMBUH.iloc[-1]
S0

33159

In [115]:
#Let us first create en empty matrix such as daily returns
sem_list = np.zeros_like(daily_returns)
sem_list[0] = S0
sem_list

array([[33159., 33159., 33159., ..., 33159., 33159., 33159.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

In [116]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    sem_list[t] = sem_list[t - 1] * daily_returns[t]
sem_list = pd.DataFrame(sem_list)
sem_list.head()

0             1     ...          9998          9999
0  33159.000000  33159.000000  ...  33159.000000  33159.000000
1  33384.184170  33717.302377  ...  33830.131979  33653.095562
2  33768.719892  34209.074400  ...  34081.342850  33862.071626
3  33967.211846  34351.087775  ...  34347.675149  34227.372325
4  34326.577583  34778.687962  ...  34697.806109  34388.070750

[5 rows x 10000 columns]

In [117]:
sembuh = data.SEMBUH
sembuh = pd.DataFrame(sembuh)
frames = [sembuh, sem_list]
monte_carlo_forecast = pd.concat(frames)

In [118]:
#Let us first create en empty matrix such as daily returns
sem_list = np.zeros_like(daily_returns)
sem_list[0] = S0
sem_list

array([[33159., 33159., 33159., ..., 33159., 33159., 33159.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

In [119]:
# With a simple for loop, we are going to forecast the next 250 days
for t in range(1, t_intervals):
    sem_list[t] = sem_list[t - 1] * daily_returns[t]

In [120]:
sembuh_new = np.zeros([t_intervals,1])
sembuh_new

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [121]:
for t in range(0, t_intervals):
  sembuh_new[t] = sum(sem_list[t,:])/iterations
#sembuh_new = pd.DataFrame(sembuh_new)
#sembuh_new.head()

Perbandingan Gap antara hasil prediksi dengan data real.

In [124]:
real = np.array(data_covid.loc[247:,'SEMBUH'])
real

array([33253, 33317, 33376, 33442, 33522, 33606, 33679, 33730, 33770,
       33820, 33887, 33972, 34068, 34160, 34248, 34328, 34433, 34480,
       34594, 34692])

In [125]:
gap = np.zeros([20,1])
for t in range(0, t_intervals):
  gap[t] = abs(real[t]-sembuh_new[t])/real[t]*100

In [126]:
real = real.reshape((20,1))
real.shape
real

array([[33253],
       [33317],
       [33376],
       [33442],
       [33522],
       [33606],
       [33679],
       [33730],
       [33770],
       [33820],
       [33887],
       [33972],
       [34068],
       [34160],
       [34248],
       [34328],
       [34433],
       [34480],
       [34594],
       [34692]])

In [127]:
sembuh_new = pd.DataFrame(sembuh_new)
real = pd.DataFrame(real)
gap = pd.DataFrame(gap)

In [128]:
tabel = pd.DataFrame(real)

In [129]:
tabel['prediksi'] = sembuh_new
tabel['gap'] = gap

In [130]:
tabel

0      prediksi        gap
0   33253  33159.000000   0.282681
1   33317  33415.404569   0.295358
2   33376  33674.676185   0.894883
3   33442  33937.966027   1.483063
4   33522  34199.682571   2.021605
5   33606  34461.294488   2.545065
6   33679  34728.235044   3.115398
7   33730  34996.641874   3.755238
8   33770  35267.586843   4.434666
9   33820  35540.405289   5.086946
10  33887  35814.324436   5.687504
11  33972  36093.348583   6.244403
12  34068  36371.763626   6.762251
13  34160  36653.552857   7.299628
14  34248  36939.372222   7.858480
15  34328  37224.427444   8.437507
16  34433  37512.832364   8.944421
17  34480  37805.909613   9.645910
18  34594  38099.294615  10.132666
19  34692  38394.530961  10.672579

**I'm intended to make an hybid model with monte carlo simulation, arma model and maybe LSTM.  
So, to be continued...
I'm open to any kind of suggestion:)**